module.exports = {
    config: {
      updateChannel: 'stable',
      fontSize: 19,
      fontFamily: 'Dank Mono, Consolas, "Lucida Console", monospace',
      fontWeight: 'normal',
      fontWeightBold: 'bold',
      cursorColor: 'rgba(248,28,229,0.8)',
      cursorAccentColor: '#000',
      cursorShape: 'BLOCK',
      cursorBlink: false,
      foregroundColor: '#fff',
      backgroundColor: '#000',
      selectionColor: 'rgba(248,28,229,0.3)',
      css: '',
      termCSS: '',
      showWindowControls: '',
      windowSize: [800, 450],
      shell: '',
      shellArgs: ['--login'],
      env: {},
      bell: 'SOUND',
      copyOnSelect: false,
      defaultSSHApp: true,
    },
    plugins: ["hypercwd", "hyperlinks", "hyperterm-tab-icons", "hyper-material-theme"],
    localPlugins: []
  };